#!/usr/bin/env bash
# a script that transfers a file to a server
# accepts four parameters

if [ "$#" -ne 4 ]
then
echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
scp -o StrictHostkeyChecking=no -i "$4" "$1" "$3@$2":~
fi

