#!/usr/bin/env bash
# configure nginx to redirect to another page

sudo apt-get -y install nginx
sudo bash -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
redirect="\n\tlocation /redirect_me {\nreturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n}\n"
sudo sed -i "53s|.*|$redirect|" /etc/nginx/sites-enabled/default
sudo /etc/init.d/nginx restart