#!/usr/bin/env bash
# configure web-02 to be identical to web-01

sudo apt-get update
sudo apt-get -y install nginx

sudo ufw allow 'Nginx HTTP'
sudo service nginx restart

sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www/html

sudo mv /var/www/html/index.nginx-debian.html /var/www/html/index-nginx-debian.html.bak
echo "Hello, World!" | sudo tee /var/www/html/index-nginx-debian.html > /dev/null

sudo sed -i '/server_name _;/a \\tadd_header X-Served-By $hostname;' /etc/nginx/sites-available/default

sudo nginx -t

sudo service nginx restart
