#!/usr/bin/env bash
#this script displays to infinity and beyondindefinitelywithasleep2inbetweeniterationandiamivincible!!!whenrecievingasigtermsignal
trap 'echo "I am invincible!!!"' SIGTERM
while :
do
echo "To infinity and beyond"
sleep 2
done

