#!/usr/bin/env bash
#this script displays badluck at the 4th iteration
#this script displays goodluck at the 8th iteration
#this script displays "Best School" for the rest iterations 
i=1
while [ $i -le 10 ];
do
if [ $i -eq 4 ]
then
echo "bad luck"
elif [ $i -eq 8 ]
then
echo "good luck"
else
echo "Best School"
fi
((i++))
done

